/**
 * Export the emotion art as a framed, standalone image (PNG download).
 */

import jsPDF from 'jspdf';
import type { EmotionFrame, EmotionLabel } from '../types/emotions';
import { generateEmotionArt } from './emotionArt';

const EMOTION_PALETTE_FIRST: Record<EmotionLabel, string> = {
  joy: '#E8B931', sadness: '#6B8DAE', anger: '#C4614E',
  fear: '#8B6BAE', surprise: '#4EA88B', disgust: '#7A8B5E', neutral: '#A8A08E',
};

export function exportFramedArt(frames: EmotionFrame[], sessionId: string) {
  const ART_W = 1400;
  const ART_H = 1050;
  const FRAME_PAD = 48;
  const BOTTOM_BAR = 80;
  const TOTAL_W = ART_W + FRAME_PAD * 2;
  const TOTAL_H = ART_H + FRAME_PAD * 2 + BOTTOM_BAR;

  const canvas = document.createElement('canvas');
  canvas.width = TOTAL_W;
  canvas.height = TOTAL_H;
  const ctx = canvas.getContext('2d')!;

  // Frame background
  ctx.fillStyle = '#FDFBF8';
  ctx.fillRect(0, 0, TOTAL_W, TOTAL_H);

  // Subtle border
  ctx.strokeStyle = '#E8E4DD';
  ctx.lineWidth = 1;
  ctx.strokeRect(FRAME_PAD - 1, FRAME_PAD - 1, ART_W + 2, ART_H + 2);

  // Generate and draw art
  const { canvas: artCanvas, artist } = generateEmotionArt(frames, ART_W, ART_H);
  ctx.drawImage(artCanvas, FRAME_PAD, FRAME_PAD);

  // Bottom info bar
  const infoY = FRAME_PAD + ART_H + 24;

  // Title + artist
  ctx.font = 'italic 18px Georgia, "Playfair Display", serif';
  ctx.fillStyle = '#2C2A26';
  ctx.textAlign = 'left';
  ctx.fillText('Emotional Fingerprint', FRAME_PAD, infoY);
  ctx.font = '13px -apple-system, "Inter", sans-serif';
  ctx.fillStyle = '#A8A08E';
  ctx.fillText(`Inspired by ${artist.fullName}`, FRAME_PAD, infoY + 18);

  // Date
  ctx.font = '12px -apple-system, "Inter", sans-serif';
  ctx.fillStyle = '#B0A99E';
  ctx.fillText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), FRAME_PAD, infoY + 34);

  // Emotion color palette dots
  const emotions = (Object.keys(EMOTION_PALETTE_FIRST) as EmotionLabel[]).filter(e => {
    return frames.some(f => f.emotion_distribution[e] > 0.1);
  });
  const dotStartX = TOTAL_W - FRAME_PAD - emotions.length * 24;
  emotions.forEach((emotion, i) => {
    ctx.beginPath();
    ctx.arc(dotStartX + i * 24, infoY - 4, 6, 0, Math.PI * 2);
    ctx.fillStyle = EMOTION_PALETTE_FIRST[emotion];
    ctx.fill();
  });

  // EmotionsAI watermark
  ctx.font = '10px -apple-system, "Inter", sans-serif';
  ctx.fillStyle = '#D4CFC7';
  ctx.textAlign = 'right';
  ctx.fillText('EmotionsAI', TOTAL_W - FRAME_PAD, infoY + 34);

  // Download as PNG
  const link = document.createElement('a');
  link.download = `emotional-fingerprint-${sessionId.slice(0, 8)}.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}

/**
 * Export analytics PDF with disclaimer.
 */
export function exportAnalyticsPDF(frames: EmotionFrame[], sessionId: string, notes: string[]) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const M = 20;
  const CW = W - M * 2;
  let y = M;

  const hexRgb = (hex: string): [number, number, number] => [
    parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16),
  ];

  // ── Disclaimer banner ───────────────────────────────────────────────
  pdf.setFillColor(255, 248, 240);
  pdf.roundedRect(M, y, CW, 20, 3, 3, 'F');
  pdf.setDrawColor(196, 148, 106);
  pdf.setLineWidth(0.3);
  pdf.roundedRect(M, y, CW, 20, 3, 3, 'S');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.setTextColor(196, 148, 106);
  pdf.text('Important Notice', M + 6, y + 7);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(100, 95, 85);
  pdf.text('This report is generated by an observational tool and may not be fully precise.', M + 6, y + 12);
  pdf.text('It is not a clinical or diagnostic assessment. All emotion readings are probabilistic estimates.', M + 6, y + 16);
  y += 26;

  // ── Header ──────────────────────────────────────────────────────────
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  pdf.setTextColor(44, 42, 38);
  pdf.text('EmotionsAI', M, y + 8);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(122, 117, 107);
  pdf.text('Analytics Report', M, y + 15);

  pdf.setFontSize(9);
  pdf.text(`Session: ${sessionId.slice(0, 18)}...`, W - M, y + 8, { align: 'right' });
  pdf.text(`Date: ${new Date().toLocaleString()}`, W - M, y + 15, { align: 'right' });
  y += 24;

  // ── Stats ───────────────────────────────────────────────────────────
  const dur = frames.length * 2;
  const mins = Math.floor(dur / 60);
  const secs = dur % 60;
  const avgValence = frames.reduce((s, f) => s + f.dimensional_model.valence, 0) / frames.length;
  const avgStress = frames.reduce((s, f) => s + f.flags.stress_level, 0) / frames.length;

  const stats = [
    { label: 'Duration', value: `${mins}m ${secs.toString().padStart(2, '0')}s` },
    { label: 'Frames', value: String(frames.length) },
    { label: 'Avg Valence', value: `${avgValence >= 0 ? '+' : ''}${avgValence.toFixed(2)}` },
    { label: 'Avg Stress', value: `${Math.round(avgStress * 100)}%` },
  ];

  const boxW = CW / stats.length - 2;
  stats.forEach((s, i) => {
    const bx = M + i * (boxW + 2.5);
    pdf.setFillColor(245, 242, 237);
    pdf.roundedRect(bx, y, boxW, 16, 2, 2, 'F');
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(120, 115, 107);
    pdf.text(s.label, bx + boxW / 2, y + 5, { align: 'center' });
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(11);
    pdf.setTextColor(44, 42, 38);
    pdf.text(s.value, bx + boxW / 2, y + 12, { align: 'center' });
  });
  y += 22;

  // ── Emotion distribution ────────────────────────────────────────────
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.setTextColor(44, 42, 38);
  pdf.text('Emotion Distribution', M, y);
  y += 6;

  const avgDist: Record<string, number> = {};
  (Object.keys(frames[0].emotion_distribution) as EmotionLabel[]).forEach(e => {
    avgDist[e] = frames.reduce((s, f) => s + f.emotion_distribution[e], 0) / frames.length;
  });
  const sorted = (Object.entries(avgDist) as [EmotionLabel, number][]).sort((a, b) => b[1] - a[1]);

  sorted.forEach(([emotion, value]) => {
    const barW = CW * 0.5;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(80, 76, 72);
    pdf.text(emotion.charAt(0).toUpperCase() + emotion.slice(1), M, y + 4);
    const [r, g, b] = hexRgb(EMOTION_PALETTE_FIRST[emotion]);
    pdf.setFillColor(r, g, b);
    pdf.roundedRect(M + 28, y, barW * value, 5, 1, 1, 'F');
    pdf.setFillColor(232, 228, 221);
    pdf.roundedRect(M + 28 + barW * value, y, barW * (1 - value), 5, 1, 1, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    pdf.setTextColor(44, 42, 38);
    pdf.text(`${Math.round(value * 100)}%`, M + 28 + barW + 3, y + 4);
    y += 8;
  });
  y += 6;

  // ── Timeline ────────────────────────────────────────────────────────
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.setTextColor(44, 42, 38);
  pdf.text('Emotional Timeline', M, y);
  y += 6;

  const chartH = 30;
  pdf.setFillColor(245, 242, 237);
  pdf.roundedRect(M, y, CW, chartH, 2, 2, 'F');

  // Valence line
  pdf.setDrawColor(107, 174, 122);
  pdf.setLineWidth(0.8);
  for (let i = 1; i < frames.length; i++) {
    const x1 = M + ((i - 1) / (frames.length - 1)) * CW;
    const x2 = M + (i / (frames.length - 1)) * CW;
    const y1 = y + chartH - ((frames[i - 1].dimensional_model.valence + 1) / 2) * chartH;
    const y2 = y + chartH - ((frames[i].dimensional_model.valence + 1) / 2) * chartH;
    pdf.line(x1, y1, x2, y2);
  }

  // Stress line
  pdf.setDrawColor(196, 97, 78);
  pdf.setLineWidth(0.5);
  for (let i = 1; i < frames.length; i++) {
    const x1 = M + ((i - 1) / (frames.length - 1)) * CW;
    const x2 = M + (i / (frames.length - 1)) * CW;
    const y1 = y + chartH - frames[i - 1].flags.stress_level * chartH;
    const y2 = y + chartH - frames[i].flags.stress_level * chartH;
    pdf.line(x1, y1, x2, y2);
  }
  y += chartH + 10;

  // ── Notes ──────────────────────────────────────────────────────────
  if (notes.length > 0) {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(44, 42, 38);
    pdf.text('Notes', M, y);
    y += 6;
    notes.forEach(n => {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(80, 76, 72);
      pdf.text(`• ${n}`, M + 4, y);
      y += 6;
    });
    y += 4;
  }

  // ── Footer disclaimer ──────────────────────────────────────────────
  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(7);
  pdf.setTextColor(176, 169, 158);
  pdf.text('EmotionsAI is an observational wellness tool, not a diagnostic instrument. All readings are probabilistic estimates', W / 2, pageH - 14, { align: 'center' });
  pdf.text('based on facial expression recognition and may not reflect your actual emotional state with full accuracy.', W / 2, pageH - 10, { align: 'center' });
  pdf.text('This report should not be used for clinical, diagnostic, or medical purposes.', W / 2, pageH - 6, { align: 'center' });

  pdf.save(`emotions-analytics-${sessionId.slice(0, 8)}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
